parameters:
  smartesb.consumers.queue.class: Smartbox\Integration\FrameworkBundle\Components\Queues\QueueConsumer
  smartesb.consumers.csv.class: Smartbox\Integration\FrameworkBundle\Components\FileService\Csv\CsvConfigurableConsumer

services:
  smartesb.consumers.queue:
      class: %smartesb.consumers.queue.class%
      calls:
          - [ setId, ['smartesb.consumers.queue']]
          - [ setSmartesbHelper, [@smartesb.helper]]

  smartesb.consumers.generic_csv:
      class: "%smartesb.consumers.csv.class%"
      description: A Generic Consumer for csv files
      calls:
          - [ setId, ['smartesb.consumers.generic_csv']]
          - [setConfigurableStepsProvider,[@smartesb.steps_provider.csv_file]]

      options:
          stop_on_eof: true
          batch_size: 1

      methods:
          read_lines:
              description: Read from a csv file batch_size lines at a time

              query_steps:
                  - read_lines:
                      result_name: xxx
                      max_lines: eval: batch_size

              query_result:
                  csv: eval: results['xxx']

              on_consume: ~