parameters:
  ########## PROTOCOL CLASSES  ##########
  smartesb.protocols.base.class: Smartbox\Integration\FrameworkBundle\Core\Protocols\Protocol
  smartesb.protocols.direct.class: Smartbox\Integration\FrameworkBundle\Core\Protocols\DirectProtocol
  smartesb.protocols.json_file.class: Smartbox\Integration\FrameworkBundle\Components\JsonFileLoader\JsonFileLoaderProtocol
  smartesb.protocols.queue.class: Smartbox\Integration\FrameworkBundle\Components\Queues\QueueProtocol
  smartesb.protocols.configurable.nosql.class: Smartbox\Integration\FrameworkBundle\Components\DB\NoSQL\NoSQLConfigurableProtocol
  smartesb.protocols.configurable.webservice.class: Smartbox\Integration\FrameworkBundle\Components\WebService\ConfigurableWebserviceProtocol
  smartesb.protocols.configurable.rest.class: Smartbox\Integration\FrameworkBundle\Components\WebService\Rest\RestConfigurableProtocol
  smartesb.protocols.configurable.soap.class: Smartbox\Integration\FrameworkBundle\Components\WebService\Soap\SoapConfigurableProtocol
  smartesb.protocols.configurable.dbal.class: Smartbox\Integration\FrameworkBundle\Components\DB\Dbal\ConfigurableDbalProtocol
  smartesb.protocols.service.class: Smartbox\Integration\FrameworkBundle\Components\SymfonyService\SymfonyServiceProtocol
  smartesb.protocols.csv_file.class: Smartbox\Integration\FrameworkBundle\Components\FileService\Csv\CsvConfigurableProtocol

services:
  ########## PROTOCOLS  ##########

  # Base
  smartesb.protocols.base:
      class: %smartesb.protocols.base.class%

  # Direct
  smartesb.protocols.direct:
      class: %smartesb.protocols.direct.class%
      calls:
        - [setDefaultProducer, ['@smartesb.producer.direct']]
        - [setDefaultHandler, ['@smartesb.handlers.sync']]

  # JSON FILE
  smartesb.protocols.json_file:
      class: %smartesb.protocols.json_file.class%
      calls:
        - [setDefaultProducer, ['@smartesb.producers.json_file']]

  # Queues
  smartesb.protocols.service:
      class: %smartesb.protocols.service.class%
      calls:
        - [setDefaultProducer, ['@smartesb.producers.service']]
        - [setDefaultHandler, ['@smartesb.handlers.async']]

  # Queues
  smartesb.protocols.queue:
      class: %smartesb.protocols.queue.class%
      calls:
        - [setDefaultProducer, ['@smartesb.producers.queue']]
        - [setDefaultConsumer, ['@smartesb.consumers.queue']]
        - [setDefaultHandler, ['@smartesb.handlers.async']]

  #NoSQL
  smartesb.protocols.configurable.nosql:
      class: %smartesb.protocols.configurable.nosql.class%
      calls:
       - [setDefaultHandler, ['@smartesb.handlers.async']]

  smartesb.protocols.configurable.webservice:
      class: %smartesb.protocols.configurable.webservice.class%

  smartesb.protocols.configurable.rest:
      class: %smartesb.protocols.configurable.rest.class%

  smartesb.protocols.configurable.soap:
      class: %smartesb.protocols.configurable.soap.class%

  smartesb.protocols.configurable.dbal:
      class: %smartesb.protocols.configurable.dbal.class%
      calls:
        - [setDefaultHandler, ['@smartesb.handlers.async']]

  # Csv File
  smartesb.protocols.configurable.csv_file:
      class: "%smartesb.protocols.csv_file.class%"
      calls:
        - [setDefaultHandler, ['@smartesb.handlers.async']]
